### ISSUE TITLE
KB data

### ISSUE THREAD

**Issue by shuaichenchang** [jonathanherzig/zero-shot-semantic-parsing#2]
Hi Jonathan,
I am wondering where I can find the KB data instead of utterance-lambdaDCS pairs. I thought it should be in the evaluator folder since evaluator is able to execute queries, but I cannot find any files about the KB triples.

**Comment by jonathanherzig** [comment]
Hi Shuaichen,
The KBs themselves are generated each time the evaluator runs, using the code in SimpleWorld.java which is in /evaluator⁩/⁨sempre⁩/⁨libsempre/sempre-overnight.jar .

**Comment by berlino** [comment]
Hi, @shuaichenchang   Did you manage to get the knowledge base out of SimpleWorld.java?  
It seems databases are create on the fly during evaluation.

**Comment by shuaichenchang** [comment]
@berlino  Yes, I found that in the SimpleWorld code. Thank you for letting me know.

**Comment by berlino** [comment]
@shuaichenchang Did you extract all the triples from SimpleWorld? If so, would mind sharing your way of doing that? 

I guess  one workaround is to exact them indirectly from the executor. There should be a better way. 

Edited: I manage to extract them from the executor by expressions like listValue ( getProperty (entity property ) ).
